language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

#env:

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.5
      env:
      - TOXENV=flake8
      - TOXPYTHON=python3.5
    - python: 3.5
      env:
      - TOXENV=pylint
      - TOXPYTHON=python3.5
    - python: 3.5
      env:
      - TOXENV=docs
      - TOXPYTHON=python3.5
    - python: 3.5
      env:
      - TOXENV=check-manifest
      - TOXPYTHON=python3.5
    - python: 3.5
      env:
      - TOXENV=checkreadme
      - TOXPYTHON=python3.5

before_install:
  - pip install codecov # for coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov
